name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags:
      - "v*"
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  build:
    name: Build Executables
    needs: test
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: win
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: macos-latest
            platform: macos
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build executable
        run: |
          mkdir -p dist
          npx pkg . --targets node18-${{ matrix.platform }}-${{ matrix.arch }} --out-path dist/

      - name: Rename executable (Windows)
        if: matrix.platform == 'win'
        run: |
          cd dist
          mv wsei-course-downloader.exe wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}.exe

      - name: Rename executable (Unix)
        if: matrix.platform != 'win'
        run: |
          cd dist
          mv wsei-course-downloader wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}*

      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/v') && matrix.platform == 'linux' && matrix.arch == 'x64'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            🎉 **WSEI Course Downloader ${{ github.ref_name }}**

            Professional automated course material downloader for WSEI e-learning platform.

            ## 📦 Downloads
            - **Linux x64**: `wsei-downloader-linux-x64`
            - **Windows x64**: `wsei-downloader-win-x64.exe`  
            - **macOS Intel**: `wsei-downloader-macos-x64`
            - **macOS Apple Silicon**: `wsei-downloader-macos-arm64`

            ## 🚀 Usage
            1. Download the appropriate binary for your platform
            2. Make it executable: `chmod +x wsei-downloader-*` (Linux/macOS)
            3. Run: `./wsei-downloader-*` or `wsei-downloader-*.exe`
            4. Follow the setup wizard to configure your credentials

            ## ⚠️ Requirements
            - Chrome browser must be installed separately
            - Run `node install-chrome.js` or install Chrome manually

            Built with ❤️ for WSEI students and educators.
          draft: false
          prerelease: false

      - name: Upload to release (existing release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'win' && '.exe' || '' }}
          asset_name: wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'win' && '.exe' || '' }}
          asset_content_type: application/octet-stream

      - name: Get release upload URL (for tag-triggered builds)
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            return release.data.upload_url;

      - name: Upload to release (tag-triggered)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.result || steps.create_release.outputs.upload_url }}
          asset_path: dist/wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'win' && '.exe' || '' }}
          asset_name: wsei-downloader-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.platform == 'win' && '.exe' || '' }}
          asset_content_type: application/octet-stream

  build-validation:
    name: Build Validation
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name != 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test build process
        run: |
          mkdir -p dist
          npx pkg . --targets node18-linux-x64 --out-path dist/
          ls -la dist/
          echo "Testing executable startup (Chrome not found error is expected):"
          timeout 10 ./dist/wsei-course-downloader || echo "Build validation complete - executable starts correctly"
